# Generated by Django 6.0.2 on 2026-02-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                (
                    "horario",
                    models.CharField(
                        default="Lunes a Sábado: 9am - 8pm", max_length=100
                    ),
                ),
            ],
        ),
    ]
