# Generated by Django 6.0.2 on 2026-02-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("marca", models.CharField(default="San Agustín", max_length=100)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("acetato", "Acetato"),
                            ("metal", "Metal"),
                            ("titanio", "Titanio"),
                            ("mixto", "Mixto (Acetato/Metal)"),
                        ],
                        default="acetato",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("negro", "Negro"),
                            ("havana", "Havana (Carey)"),
                            ("transparente", "Transparente"),
                            ("dorado", "Dorado"),
                            ("plateado", "Plateado"),
                            ("azul", "Azul"),
                        ],
                        default="negro",
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=10)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.categoria",
                    ),
                ),
            ],
        ),
    ]
